### ISSUE TITLE
UI misalignment in VCV Rack

### ISSUE THREAD

**Issue by niektb** [ohmtech-rdi/eurorack-blocks#481]
Hi all! I stumbled across this project recently and it looks really interesting as I've been a user of both VCV and Faust and this seems to combine it really nicely. However, when trying to build some of the examples the elements of the UI seem to be misaligned! I'm not sure if I misconfigured anything but here is a screenshot! (notice also that the modules are placed against each other but there is still a gap)
![image](https://user-images.githubusercontent.com/1948785/229899611-df1706c5-374a-40f5-ba73-9021506364b3.png)

**Comment by ohmtech-rdi** [comment]
Hi @niektb !

Yes, the SVG seems to be shrinked in both dimensions. The screw placement is fine though, so I guess it's really about the SVG. I can see also that the font is not the proper one for Drop and LowPass (which is supposed to use the installed ones), see screenshot on how it should look:

![image](https://user-images.githubusercontent.com/11056842/230577170-4da23a35-5ab5-4ba4-a3d2-5163231c96e6.png)

- Could you please give me some information on which platform you are using? (ie Windows, MacOS or Linux?)
- Did anything went smoothly while installing?

Thanks!

**Comment by niektb** [comment]
Hi @ohmtech-rdi 

I'm on Windows 11! 
Installation went not supersmooth as in I had some troubles with Chocolatey (installation of packages hung after asking for installation confirmation) so I had to redo the process. (I believe I solved that by enabling GlobalConfirmation). Doesn't sound very related to me though. 
I had to also play around with the environment variables. I use OneDrive to backup My Documents so VCVRack could not find the modules (that were placed in the 'normal' My Documents). So I had to reinstall the VCV libraries after setting the ENV Variable like this:
![image](https://user-images.githubusercontent.com/1948785/230607664-d8babaff-3382-4d5d-8b61-7289763193c1.png)
 Hope this information helps but feel free to ask for more details! :)

**Comment by ohmtech-rdi** [comment]
Hi @niektb 

I'll need to install Windows 11 in a VM to give it a try :)

In the meantime, could you please send the `panel_vcvrack.svg` of the `drop` Sample? It is located in the `artifacts` folder, so here:

```
eurorack-blocks/samples/drop/artifacts/panel_vcvrack.svg
```

I'll check if there are any differences by the one produced on other platforms. If not, then maybe it's something specific to Rack that I would need to investigate.

**Comment by niektb** [comment]
Hi @ohmtech-rdi 

Sure! Here it is:
![panel_vcvrack](https://user-images.githubusercontent.com/1948785/230739385-6c180ea2-21a0-4bdb-b977-df62291d5e54.svg)

**Comment by ohmtech-rdi** [comment]
Hi @niektb 

Thanks for the svg!

So looking at the files, it seems that our cairo dependency changed again how to write files, and that must confuse VCV Rack for some reason.

This is the diff of the first line:
```diff
< <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="172.8" height="364.251969" viewBox="0 0 172.8 364.251969">
---
> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="172.8pt" height="364.251969pt" viewBox="0 0 172.8 364.251969" version="1.1">
```

(first line is yours, second line is mine).

So it seems that for some reason already units and version are missing.

I'll investigate that more, but I think I'll have to get rid of cairo (this graphic library dependency is one of the biggest pain point in the project), and that might take some time.

**Comment by ohmtech-rdi** [comment]
@niektb could you please checkout the `wip-force-cairo-pt` branch and give `erbb configure` on the sample `drop` another go and send again the generated `eurorack-blocks/samples/drop/artifacts/panel_vcvrack.svg` file?

(please don't hesitate to ask if it's not clear how to do that)

Thanks!

**Comment by niektb** [comment]
@ohmtech-rdi: here is the new svg!
![panel_vcvrack](https://user-images.githubusercontent.com/1948785/231406441-7bdcc10e-cf69-455a-9c6c-126348371a7c.svg)
It looks much better now in VCV!!
![image](https://user-images.githubusercontent.com/1948785/231406608-a3db7b49-8c75-442d-a057-8b7a38df685b.png)

**Comment by ohmtech-rdi** [comment]
@niektb Great! So that's one issue fixed in a portable way.

The other one is related on how freetype and cairo interacts. Not sure why this happens yet. I think it selects the wrong font to start with, hopefully that would be the only issue. I'll investigate that.

**Comment by ohmtech-rdi** [comment]
@niektb Sorry for the delay

- Can you please check if you can see the file `D-DIN.otf` in your `C:\windows\fonts` directory?
- Could it be also that your filesystem is setup to be case sensitive?

Thanks!

**Comment by ohmtech-rdi** [comment]
Ok, so I'm really not sure what is going on your side, it seems to work well here.
However:
- Cairo on windows returns different sort of font metrics than macOS or Linux, it's quite broken, but I was able to make a fix in #505 that almost correct the problem
- Cairo can't seem to select the right bold font we use anyway, and I'm not sure why as this is a separate `otf` file

All in all, this is really broken on Windows, and we would need to get rid of cairo font handling completely.

Also, I should mention there is always the workaround of using a custom image, where you would vectorise your text, and this should work properly.

I still really want to know if there was simply a problem with the font copy, and actually the font are not installed for some reasons @niektb 

Thanks!

**Comment by niektb** [comment]
Hi @ohmtech-rdi : thanks for getting back to me! I cannot find the D-DIN.otf in the directory mentioned!
So maybe it's an easy fix? But then again, since the alignment issue is fixed I'm actually already quite happy (the 'wrong' font is a little less pretty but it's acceptable. Just add it to the list of known bugs in case others stumble across it and i'm alright :)

**Comment by ohmtech-rdi** [comment]
@niektb Thanks for the response! Indeed, if you can't find the font, it's normal that it substitutes it with another one.

The alignment I'm talking about are quite subtle in general. What you had was really improper rendering of font because of pycairo, I don't think that's going to change.

But! If you copy manually the fonts in your fonts folder, I think that would solve the problem.

**Comment by ohmtech-rdi** [comment]
@niektb The fonts are in:
```
eurorack-blocks/include/erb/vcvrack/design
```

Then you need to copy the *content* of each folder into `C:\Windows\Fonts`

So typically you would have:
```
C:\Windows\Fonts\D-DIN-Bold.otf
C:\Windows\Fonts\D-DIN-Italic.otf
C:\Windows\Fonts\D-DIN.otf
C:\Windows\Fonts\D-DINCondensed-Bold.otf
C:\Windows\Fonts\D-DINCondensed.otf
C:\Windows\Fonts\D-DINExp-Bold.otf
C:\Windows\Fonts\D-DINExp-Italic.otf
C:\Windows\Fonts\D-DINExp.otf
...
```

Could you please try that and tell me if you have now proper panels please? :-)

**Comment by ohmtech-rdi** [comment]
@niektb FYI https://github.com/ohmtech-rdi/eurorack-blocks/pull/519

We implemented what we said last week:

> All in all, this is really broken on Windows, and we would need to get rid of cairo font handling completely.

So we are now using Freetype on all 3 platforms (Windows, macOS and Linux) to achieve consistent looks across platforms. Since the fonts do not need to be copied in your Windows fonts folder, we hope this will work out of the box.

I'll try soon myself on Windows, but if you want to give it a try, this is sitting on the branch `panel-freetype`

**Comment by ohmtech-rdi** [comment]
So as far as I have tested, this looks the same on all platforms.

If it still doesn't work on Windows 11, please make a new issue for that problem.

**Comment by niektb** [comment]
Hey I tried this and it looks amazing! Thank you very much!
