### ISSUE TITLE
bash: erbb: command not found on Max

### ISSUE THREAD

**Issue by eliottparis** [ohmtech-rdi/eurorack-blocks#544]
After following the [documentation](https://eurorack-blocks.readthedocs.io/en/latest/max/setup.html) to setup `erbb`, I'm unable to build the [`Reverb.maxpat`](https://github.com/ohmtech-rdi/eurorack-blocks/blob/main/max/reverb/Reverb.maxpat) example.

The `erb.build.js` fails with the following error:

```
...
node.script: Build starting
node.script: Error: bash: erbb: command not found
node.script: Error: bash: erbb: command not found
node.script: child process exited with code 127
```

It seems that Max can't find the path to `erbb`.

A possible solution would be to execute the `erbb` commands by giving either an absolute or relative path to the `erbb` file.

**Comment by ohmtech-rdi** [comment]
Yep indeed, on recent versions of macOS, `zsh` is used so that must come from that. Using an absolute or relative path to `erbb` and invoking it directly using `python3` instead of having all this going through a shell seems to be indeed a better and more robust solution 👍
