### ISSUE TITLE
windows / max "modulenotfounderror" "no module name soundfile found"

### ISSUE THREAD

**Issue by garrett-laroy-johnson** [ohmtech-rdi/eurorack-blocks#597]
Having this issue both when generating a VCV by saving a Max folder or when I go to init a new module in CL. 

![image](https://github.com/ohmtech-rdi/eurorack-blocks/assets/6713092/04f2faf2-54ae-45b1-b4b3-d809f2b07c8a)

![image](https://github.com/ohmtech-rdi/eurorack-blocks/assets/6713092/74416f7e-fd32-4ed7-9b02-8285940e19be)

**Comment by ohmtech-rdi** [comment]
Hi @garrett-laroy-johnson

Did you run `erbb setup --with-max-support`?

In all cases please run it, and please copy/paste the output of this command here. In particular I'm interested in any errors, or if `erbb` could check the toolchain (because it tries to load soundfile at that time).

Thanks!

**Comment by garrett-laroy-johnson** [comment]
Hi Rapheal,

I cloned a clean repo, reinstalled Python, and don't seem to be having that
issue any longer :)

**Comment by ohmtech-rdi** [comment]
Hi @garrett-laroy-johnson Ok great, I'll closed the issue as magically solved 🙂
