### ISSUE TITLE
Wrong plugin path on windows (plugins-win-x64)

### ISSUE THREAD

**Issue by MathiasSchneider-fr** [ohmtech-rdi/eurorack-blocks#619]
Hello, I recently installed version 2.4.1 of VCV rack on Windows (it was a first installation, not an update, VCV rack had never been installed on this machine) and the installation worked for me. created a rack2/plugins-win-x64 directory and no rack2/plugins directory. So this plugins-win-x64 became the default directory in which VCV rack searches for plugins.
The construction of the Eurorack Blocks examples subsequently created the rack2/plugins directory (since it did not exist) but therefore VCV rack could not find the plugins created since it was not looking in this directory.

**Comment by ricardomatias** [comment]
Same issue with mac, the plugin should be added to the folder named "plugins-mac-x64"

**Comment by ohmtech-rdi** [comment]
Hi, thank you both for reporting.

Hmm I see a pattern here. Not sure how to handle that if I want to keep compatibility with previous versions of VCV Rack. I'll investigate on that. Please don't hesitate to comment if you find something relevant!
